# Generated by Django 5.1.7 on 2025-03-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_cart_cartitem_doctor_emergencyservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
