# Generated by Django 5.1.7 on 2025-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('video', 'Video Consultation'), ('in_clinic', 'In-Clinic Visit')], default='in_clinic', max_length=20),
        ),
    ]
